#!/usr/bin/env python
# PyMOL Visualization Script
# Generated by PyMOL Agent on 2025-08-30 16:17:40
# Request: Create a rotating movie of hemoglobin showing the heme groups as sticks

import pymol
from pymol import cmd

# Initialize PyMOL
pymol.finish_launching(['pymol', '-c'])

cmd.do('import pymol')
cmd.do('pymol.finish_launching()')
cmd.do('pymol.cmd.fetch('1HBB')')
cmd.do('pymol.cmd.show('cartoon', '1HBB')')
cmd.do('pymol.cmd.select('heme', '1HBB and resn HEM')')
cmd.do('pymol.cmd.show('sticks', 'heme')')
cmd.do('pymol.cmd.color('gray', '1HBB')')
cmd.do('pymol.cmd.color('red', 'heme')')
cmd.do('pymol.cmd.zoom('1HBB', complete=1)')
cmd.do('pymol.cmd.mset('1 x360')')
cmd.do('for i in range(360):')
cmd.do('pymol.cmd.rotate('y', 1, '1HBB')')
cmd.do('pymol.cmd.mdo(i+1, 'draw')')
cmd.do('pymol.cmd.mplay()')
cmd.do('pymol.cmd.mpng('hemoglobin_movie.png', 1, 360, ray=1)')
cmd.do('pymol.cmd.quit()')
cmd.do('2. The `select` command is used to select the heme groups. The `show` and `color` commands are used to display and color the protein and heme groups.')
cmd.do('6. If you want to display the protein and/or heme groups in a different way (e.g., as a surface, spheres, etc.), you can change the first argument to the corresponding `show` command accordingly. If you want to color the protein and/or heme groups differently, you can change the second argument to the corresponding `color` command accordingly.')
# Script execution complete
print("Visualization script completed successfully!")
